name: 0_orchestrator
on:
  workflow_dispatch:
    inputs:
      topic:
        description: "Sujet de l'histoire"
        required: true
        default: "L’ascenseur qui ne s’arrête jamais"
      fps:
        description: "Images par seconde"
        required: true
        default: "30"
      voice:
        description: "Modèle Piper"
        required: true
        default: "fr_FR-lessac-medium"
      upload_to_discord:
        description: "Publier sur Discord ?"
        required: true
        default: "true"

jobs:
  a_prompt:
    uses: ./.github/workflows/a_prompt.yml
    with:
      topic: ${{ inputs.topic }}

  b_voiceover:
    needs: a_prompt
    uses: ./.github/workflows/b_voiceover.yml
    with:
      voice: ${{ inputs.voice }}

  c_fetch_images:
    needs: a_prompt
    uses: ./.github/workflows/c_fetch_images.yml

  d_generate_subtitles:
    needs: [a_prompt, b_voiceover]
    uses: ./.github/workflows/d_generate_subtitles.yml

  e_render_video:
    needs: [b_voiceover, c_fetch_images, d_generate_subtitles]
    uses: ./.github/workflows/e_render_video.yml
    with:
      fps: ${{ inputs.fps }}

  f_publish_discord:
    if: ${{ inputs.upload_to_discord == 'true' }}
    needs: e_render_video
    uses: ./.github/workflows/f_publish_discord.yml

  g_build_media_bank:
    needs: [a_prompt, b_voiceover, c_fetch_images, d_generate_subtitles, e_render_video]
    uses: ./.github/workflows/g_build_media_bank.yml