name: Orchestrator

on:
  workflow_dispatch:
    inputs:
      images_zip:
        description: "Archive d'images (.zip)"
        required: true
        type: string
        default: outputs/images.zip

      audio_path:
        description: "Fichier audio voix/musique"
        required: true
        type: string
        default: work/audio.mp3

      captions_path:
        description: "Sous-titres (SRT/ASS) à graver"
        required: false
        type: string
        default: ""

      min_duration_sec:
        description: "Durée minimale cible (s)"
        required: false
        type: number
        default: 65

      max_duration_sec:
        description: "Durée maximale (s) — 0 = illimité"
        required: false
        type: number
        default: 0

      target_res:
        description: "Résolution cible (LxH)"
        required: false
        type: string
        default: 720x1280

      fps:
        description: "Images par seconde"
        required: false
        type: number
        default: 25

jobs:
  render_video:
    name: Render Video
    uses: ./.github/workflows/e_render_video.yml
    with:
      images_zip: ${{ inputs.images_zip }}
      audio_path: ${{ inputs.audio_path }}
      captions_path: ${{ inputs.captions_path }}
      min_duration_sec: ${{ inputs.min_duration_sec }}
      max_duration_sec: ${{ inputs.max_duration_sec }}
      target_res: ${{ inputs.target_res }}
      fps: ${{ inputs.fps }}