name: Video pipeline (one-click)

on:
  workflow_dispatch:
    inputs:
      topic:
        description: "Sujet de la vidéo"
        type: string
        required: true
      locale:
        description: "Locale (ex: fr-FR)"
        type: string
        required: true
        default: fr-FR
      media_query:
        description: "Mots-clés banque médias (horreur, peur, angoisse, etc.)"
        type: string
        required: false
        default: "horreur, peur, angoisse, frisson, cauchemar"

permissions:
  contents: read

concurrency:
  group: video-${{ github.ref }}
  cancel-in-progress: true

jobs:
  media-bank:
    uses: ./.github/workflows/g_build_media_bank.yml
    with:
      query: ${{ inputs.media_query }}
      max_items: 40
    secrets: inherit

  gen-prompt:
    uses: ./.github/workflows/a_prompt.yml
    with:
      topic: ${{ inputs.topic }}
      locale: ${{ inputs.locale }}
    secrets: inherit

  voiceover:
    needs: gen-prompt
    uses: ./.github/workflows/b_voiceover.yml
    with:
      locale: ${{ inputs.locale }}
    secrets: inherit

  # Pas de job "images" ici pour éviter les erreurs d'inputs manquants.
  # Le rendu pioche directement dans 'media-bank' (+ éventuels médias déjà fetchés).

  subtitles:
    needs:
      - gen-prompt
      - voiceover
    uses: ./.github/workflows/d_generate_subtitles.yml
    with:
      min_lines: 18
      max_lines: 24
    secrets: inherit

  render:
    needs:
      - media-bank
      - subtitles
      - voiceover
      - gen-prompt
    uses: ./.github/workflows/e_render_video.yml
    with:
      target_res: "720x1280"
      fps: 30
      min_duration_sec: 65
      max_duration_sec: 180
      mute_stock_clips: true
      subtitles_fontsize: 28
      subtitles_margin_v: 80
    secrets: inherit

  # Garde ce job uniquement si tu as bien ce workflow :
  # .github/workflows/f_publish_discord.yml
  # Sinon, supprime ce bloc.
  publish:
    needs: render
    uses: ./.github/workflows/f_publish_discord.yml
    secrets: inherit