name: 0_orchestrator
on:
  workflow_dispatch:
    inputs:
      topic:
        description: "Sujet de l'histoire d'horreur (180-200 mots)"
        required: true
        default: "Une vieille maison hantée dans les bois"
      fps:
        description: "Images par seconde de la vidéo finale"
        required: true
        default: "30"
      voice:
        description: "VoiceID ElevenLabs à utiliser"
        required: true
        default: "ELEVENLABS_VOICE_ID_ICI"

jobs:
  a_prompt:
    name: A - Generate Story Prompt
    uses: ./.github/workflows/a_prompt.yml
    with:
      topic: ${{ inputs.topic }}

  b_voiceover:
    name: B - Generate Voiceover
    needs: a_prompt
    uses: ./.github/workflows/b_voiceover.yml
    with:
      voice: ${{ inputs.voice }}

  c_fetch_images:
    name: C - Fetch Media For Video
    uses: ./.github/workflows/c_fetch_images.yml

  d_generate_subtitles:
    name: G - Generate Subtitles
    needs: [a_prompt, b_voiceover]
    uses: ./.github/workflows/d_generate_subtitles.yml

  e_render_video:
    name: E - Render Final Video
    needs: [b_voiceover, c_fetch_images, d_generate_subtitles]
    uses: ./.github/workflows/e_render_video.yml
    with:
      fps: ${{ inputs.fps }}

  f_publish_discord:
    name: F - Publish to Discord
    needs: e_render_video
    uses: ./.github/workflows/f_publish_discord.yml