name: a_prompt

on:
  workflow_call:
    inputs:
      locale: { required: true, type: string }
      topic:  { required: true, type: string }
    outputs:
      script_path:
        description: "Chemin du prompt généré"
        value: ${{ jobs.generate.outputs.script_path }}

permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      script_path: ${{ steps.meta.outputs.script_path }}
    steps:
      - uses: actions/checkout@v4

      - name: Préparer
        run: mkdir -p outputs

      - name: Générer prompt (placeholder)
        run: |
          printf "Langue=%s\nSujet=%s\n\nHistoire courte...\n" \
            "${{ inputs.locale }}" "${{ inputs.topic }}" > outputs/prompt.txt

      - name: Upload prompt
        uses: actions/upload-artifact@v4
        with:
          name: prompt_txt
          path: outputs/prompt.txt
          if-no-files-found: error
          retention-days: 7

      - id: meta
        run: echo "script_path=outputs/prompt.txt" >> "$GITHUB_OUTPUT"