name: a_prompt
on:
  workflow_call:
    inputs:
      topic:
        description: "Thème de l'histoire"
        required: true
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate story text
        run: |
          mkdir -p outputs
          echo "Sujet: ${{ inputs.topic }}" > outputs/story.txt
          echo "" >> outputs/story.txt
          echo "Il faisait nuit noire et le vent soufflait fort..." >> outputs/story.txt
          echo "Une histoire d'horreur générée automatiquement." >> outputs/story.txt

      - name: Upload story artifact
        uses: actions/upload-artifact@v4
        with:
          name: story_txt
          path: outputs/story.txt