name: B - Generate Voiceover
on:
  workflow_call:
    inputs:
      voice:
        description: "VoiceID ElevenLabs à utiliser"
        required: true
        type: string

jobs:
  generate_voice:
    runs-on: ubuntu-latest
    steps:
      - name: Download story
        uses: actions/download-artifact@v4
        with:
          name: story
          path: work

      - name: Generate voice with ElevenLabs (MP3)
        env:
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
        run: |
          set -e
          mkdir -p outputs
          text_json=$(jq -Rs . < work/story.txt)
          curl -sS -X POST "https://api.elevenlabs.io/v1/text-to-speech/${{ inputs.voice }}" \
            -H "Content-Type: application/json" \
            -H "xi-api-key: $ELEVENLABS_API_KEY" \
            -d "{\"text\":${text_json},\"voice_settings\":{\"stability\":0.5,\"similarity_boost\":0.5}}" \
            --output outputs/voice.mp3

      - name: Upload voice
        uses: actions/upload-artifact@v4
        with:
          name: voice
          path: outputs/voice.mp3
