name: b_voiceover

on:
  workflow_call:
    inputs:
      voice_id:
        required: true
        type: string
      script_path:
        required: true
        type: string
    outputs:
      voice_path:
        description: "Chemin du MP3 généré"
        value: ${{ jobs.tts.outputs.voice_path }}

permissions:
  contents: read

jobs:
  tts:
    runs-on: ubuntu-latest
    outputs:
      voice_path: ${{ steps.meta.outputs.voice_path }}
    steps:
      - uses: actions/checkout@v4

      - name: Télécharger le prompt
        uses: actions/download-artifact@v4
        with:
          name: prompt_txt
          path: .

      - name: Simuler TTS (placeholder)
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          mkdir -p outputs
          ffmpeg -f lavfi -i anullsrc=cl=stereo:r=44100 -t 3 -q:a 3 outputs/voice.mp3 -y

      - name: Publier la voix
        uses: actions/upload-artifact@v4
        with:
          name: voice_mp3
          path: outputs/voice.mp3
          if-no-files-found: error
          retention-days: 7

      - id: meta
        run: echo "voice_path=outputs/voice.mp3" >> "$GITHUB_OUTPUT"