name: b_voiceover
on:
  workflow_call:
    inputs:
      voice:
        description: "Modèle Piper à utiliser"
        required: true
        type: string

jobs:
  tts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: story_txt
          path: work

      - name: Generate voice
        run: |
          mkdir -p outputs
          echo "Simulation voix avec modèle ${{ inputs.voice }}" > outputs/voice.wav
          echo "Texte narré du fichier story.txt" >> outputs/voice.wav

      - name: Upload voice
        uses: actions/upload-artifact@v4
        with:
          name: voice_wav
          path: outputs/voice.wav