name: B - Generate Voiceover

on:
  workflow_dispatch:

jobs:
  voiceover:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download story
        uses: actions/download-artifact@v4
        with:
          name: story
          path: work

      - name: Generate voice using ElevenLabs
        run: |
          mkdir -p outputs
          TEXT=$(cat work/story.txt | jq -Rs .)
          curl -s -X POST "https://api.elevenlabs.io/v1/text-to-speech/${{ secrets.ELEVENLABS_VOICE_ID }}" \
            -H "xi-api-key: ${{ secrets.ELEVENLABS_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{\"text\":$TEXT,\"voice_settings\":{\"stability\":0.75,\"similarity_boost\":0.85}}" \
            --output outputs/voice.mp3

      - name: Upload voice
        uses: actions/upload-artifact@v4
        with:
          name: voice
          path: outputs/voice.mp3