name: c_fetch_images
on:
  workflow_call:

jobs:
  images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate placeholder images
        run: |
          mkdir -p outputs/images
          for i in {1..5}; do
            echo "Image $i" > outputs/images/img_$i.png
          done
          zip -r outputs/images.zip outputs/images

      - uses: actions/upload-artifact@v4
        with:
          name: images_zip
          path: outputs/images.zip