name: c_fetch_images

on:
  workflow_call:
    inputs:
      query:
        required: true
        type: string
      target_res:
        required: true
        type: string
    outputs:
      images_dir:
        description: "Dossier contenant les images générées"
        value: ${{ jobs.fetch.outputs.images_dir }}

permissions:
  contents: read

jobs:
  fetch:
    runs-on: ubuntu-latest
    outputs:
      images_dir: ${{ steps.meta.outputs.images_dir }}
    steps:
      - uses: actions/checkout@v4

      - name: Générer images factices
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          mkdir -p outputs/images
          RES="${{ inputs.target_res }}"
          ffmpeg -f lavfi -i color=c=black:s=$RES:d=1 -frames:v 1 outputs/images/0001.png -y
          ffmpeg -f lavfi -i color=c=gray:s=$RES:d=1  -frames:v 1 outputs/images/0002.png -y
          ffmpeg -f lavfi -i color=c=white:s=$RES:d=1 -frames:v 1 outputs/images/0003.png -y

      - name: Publier artifact images (dossier)
        uses: actions/upload-artifact@v4
        with:
          name: images_dir
          path: outputs/images
          if-no-files-found: error
          retention-days: 7

      - id: meta
        name: Exposer chemin dossier
        run: echo "images_dir=outputs/images" >> "$GITHUB_OUTPUT"