name: c_fetch_images

on:
  workflow_call:
    inputs:
      query:
        required: true
        type: string
      target_res:
        required: true
        type: string
    outputs:
      images_dir:
        description: "Dossier contenant les images générées"
        value: ${{ jobs.fetch.outputs.images_dir }}

permissions:
  contents: read

jobs:
  fetch:
    runs-on: ubuntu-latest
    outputs:
      images_dir: ${{ steps.meta.outputs.images_dir }}
    steps:
      - uses: actions/checkout@v4
      - name: Générer images factices (tests)
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          mkdir -p outputs/images
          RES="${{ inputs.target_res }}"
          # 12 images pour un slideshow fluide (suffira avec per-image 5s => 60s; le reste est pad/timing)
          for i in $(seq 1 12); do
            printf -v n "%04d" "$i"
            # Couleur variable pour debug
            case $((i%3)) in
              0) C="black" ;;
              1) C="gray" ;;
              2) C="white" ;;
            esac
            ffmpeg -f lavfi -i color=c=${C}:s=$RES:d=1 -frames:v 1 "outputs/images/${n}.png" -y
          done

      - name: Publier artifact images (dossier)
        uses: actions/upload-artifact@v4
        with:
          name: images_dir
          path: outputs/images
          if-no-files-found: error
          retention-days: 7

      - id: meta
        run: echo "images_dir=outputs/images" >> "$GITHUB_OUTPUT"