name: C - Fetch Media For Video
on:
  workflow_call:

jobs:
  select_media:
    runs-on: ubuntu-latest
    steps:
      - name: Download media bank (prebuilt)
        uses: actions/download-artifact@v4
        with:
          name: media_bank
          path: work/media_bank

      - name: Select a subset for montage
        run: |
          set -e
          mkdir -p outputs/images outputs/videos
          # On sélectionne jusqu'à 40 images et 10 vidéos (ajuste si besoin)
          find work/media_bank/images -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \) | sort | head -n 40 | while read -r f; do cp "$f" outputs/images/; done
          find work/media_bank/videos -type f -iname '*.mp4' | sort | head -n 10 | while read -r f; do cp "$f" outputs/videos/; done
          # Si pas assez de vidéos, ce n'est pas bloquant, le montage gèrera.

      - name: Upload selected media
        uses: actions/upload-artifact@v4
        with:
          name: selected_media
          path: outputs