name: C - Fetch Media For Video

on:
  workflow_dispatch:
    inputs:
      count:
        description: "Nombre d'éléments à sélectionner"
        required: true
        default: "12"

jobs:
  fetch_media:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download media bank artifact
        uses: actions/download-artifact@v4
        with:
          name: media_bank
          path: media_bank

      - name: Select random media
        run: |
          mkdir -p outputs/images
          mkdir -p outputs/videos
          shuf -n ${{ github.event.inputs.count }} -e media_bank/images/* | xargs -I{} cp {} outputs/images/
          shuf -n ${{ github.event.inputs.count }} -e media_bank/videos/* | xargs -I{} cp {} outputs/videos/

      - name: Upload selected media
        uses: actions/upload-artifact@v4
        with:
          name: selected_media
          path: outputs