name: d_generate_subtitles
on:
  workflow_call:

jobs:
  subtitles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: story_txt
          path: work

      - name: Generate subtitles
        run: |
          mkdir -p outputs
          echo "1" > outputs/captions.srt
          echo "00:00:00,000 --> 00:00:05,000" >> outputs/captions.srt
          echo "Ceci est un sous-titre test." >> outputs/captions.srt
          echo "" >> outputs/captions.srt
          echo "2" >> outputs/captions.srt
          echo "00:00:05,001 --> 00:00:10,000" >> outputs/captions.srt
          echo "Deuxième sous-titre de test." >> outputs/captions.srt

      - uses: actions/upload-artifact@v4
        with:
          name: captions_srt
          path: outputs/captions.srt