name: d_generate_subtitles

on:
  workflow_call:
    inputs:
      script_path:
        required: true
        type: string
      subtitles_fontsize:
        required: false
        type: number
      subtitles_margin_v:
        required: false
        type: number
    outputs:
      captions_path:
        description: "Chemin du SRT"
        value: ${{ jobs.subs.outputs.captions_path }}

permissions:
  contents: read

jobs:
  subs:
    runs-on: ubuntu-latest
    outputs:
      captions_path: ${{ steps.meta.outputs.captions_path }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: prompt_txt
          path: .
      - name: Générer SRT (placeholder)
        run: |
          mkdir -p outputs
          cat > outputs/subtitles.srt <<'EOF'
          1
          00:00:00,000 --> 00:00:02,000
          Titre d'intro

          2
          00:00:02,000 --> 00:00:04,000
          Sous-titres d'exemple
          EOF
      - uses: actions/upload-artifact@v4
        with:
          name: subtitles_srt
          path: outputs/subtitles.srt
          if-no-files-found: error
          retention-days: 7
      - id: meta
        run: echo "captions_path=outputs/subtitles.srt" >> "$GITHUB_OUTPUT"