name: Z - Debug Artifacts
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: story
          path: debug
        continue-on-error: true
      - uses: actions/download-artifact@v4
        with:
          name: voice
          path: debug
        continue-on-error: true
      - uses: actions/download-artifact@v4
        with:
          name: selected_media
          path: debug
        continue-on-error: true
      - uses: actions/download-artifact@v4
        with:
          name: subtitles
          path: debug
        continue-on-error: true
      - uses: actions/download-artifact@v4
        with:
          name: final_video
          path: debug
        continue-on-error: true
      - uses: actions/download-artifact@v4
        with:
          name: media_bank
          path: debug
        continue-on-error: true

      - name: List artifacts
        run: ls -R debug || true