name: Z - Debug Artifacts

on:
  workflow_dispatch:

jobs:
  debug_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: debug

      - name: List debug contents
        run: ls -R debug