name: e_render_video

on:
  workflow_call:
    inputs:
      target_res:
        required: true
        type: string
      fps:
        required: true
        type: number
      min_duration_sec:
        required: true
        type: number
      max_duration_sec:
        required: true
        type: number
      captions_path:
        required: true
        type: string
      voice_path:
        required: true
        type: string
      mute_stock_clips:
        required: true
        type: boolean
      subtitles_fontsize:
        required: true
        type: number
      subtitles_margin_v:
        required: true
        type: number
    outputs:
      video_path:
        description: "Chemin de la vidéo finale"
        value: ${{ jobs.render.outputs.video_path }}

permissions:
  contents: read

jobs:
  render:
    runs-on: ubuntu-latest
    outputs:
      video_path: ${{ steps.meta.outputs.video_path }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: images_zip
          path: .
      - uses: actions/download-artifact@v4
        with:
          name: voice_mp3
          path: .
      - uses: actions/download-artifact@v4
        with:
          name: subtitles_srt
          path: .
      - name: Installer FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg unzip
      - name: Préparer
        run: |
          mkdir -p outputs work
          unzip -o outputs/images.zip -d work
      - name: Composer vidéo (placeholder robuste)
        env:
          RES:  ${{ inputs.target_res }}
          FPS:  ${{ inputs.fps }}
          MIN:  ${{ inputs.min_duration_sec }}
          MAX:  ${{ inputs.max_duration_sec }}
          FS:   ${{ inputs.subtitles_fontsize }}
          MV:   ${{ inputs.subtitles_margin_v }}
        run: |
          ffmpeg -f lavfi -i color=c=black:s=${RES}:d=${MAX} -r ${FPS} -c:v libx264 -pix_fmt yuv420p work/base.mp4 -y
          ffmpeg -i work/base.mp4 -i outputs/voice.mp3 -shortest -c:v copy -c:a aac work/with_audio.mp4 -y
          ffmpeg -i work/with_audio.mp4 -vf "subtitles=outputs/subtitles.srt:force_style='Fontname=DejaVu Sans,Fontsize=${FS},Outline=2,Shadow=1,Alignment=5,MarginV=${MV}'" -c:a copy outputs/final.mp4 -y
      - uses: actions/upload-artifact@v4
        with:
          name: final_video_mp4
          path: outputs/final.mp4
          if-no-files-found: error
          retention-days: 7
      - id: meta
        run: echo "video_path=outputs/final.mp4" >> "$GITHUB_OUTPUT"