name: e_render_video
on:
  workflow_call:
    inputs:
      fps:
        description: "Images par seconde"
        required: true
        type: string

jobs:
  render:
    runs-on: ubuntu-latest
    env:
      FPS: ${{ inputs.fps }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: images_zip
          path: work
      - uses: actions/download-artifact@v4
        with:
          name: voice_wav
          path: work
      - uses: actions/download-artifact@v4
        with:
          name: captions_srt
          path: work

      - name: Unzip images
        run: |
          unzip -q work/images.zip -d work/images

      - name: Simulate rendering
        run: |
          mkdir -p outputs
          echo "Vidéo simulée avec FPS=${FPS}" > outputs/final.mp4
          echo "Images, audio et sous-titres intégrés." >> outputs/final.mp4

      - uses: actions/upload-artifact@v4
        with:
          name: final_mp4
          path: outputs/final.mp4