name: E - Render Final Video

on:
  workflow_dispatch:

jobs:
  render_video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download selected media
        uses: actions/download-artifact@v4
        with:
          name: selected_media
          path: work

      - name: Download voice
        uses: actions/download-artifact@v4
        with:
          name: voice
          path: work

      - name: Download subtitles
        uses: actions/download-artifact@v4
        with:
          name: subtitles
          path: work

      - name: Render video
        run: |
          mkdir -p outputs
          ls work/images/* | sort | awk '{print "file \x27"$0"\x27\nduration 5"}' > work/filelist.txt
          ffmpeg -y -f concat -safe 0 -i work/filelist.txt -i work/voice.mp3 \
            -vf "subtitles=work/captions.ass:force_style='Fontsize=20'" \
            -af "afade=t=in:ss=0:d=2,afade=t=out:st=18:d=2" \
            -c:v libx264 -pix_fmt yuv420p -c:a aac outputs/final.mp4

      - name: Upload final video
        uses: actions/upload-artifact@v4
        with:
          name: final_video
          path: outputs/final.mp4