name: F - Publish to Discord
on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: final_video
          path: work

      - name: Publish to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          set -e
          if [ -z "$DISCORD_WEBHOOK_URL" ]; then
            echo "Webhook Discord non configuré, publication annulée."
            exit 0
          fi
          curl -sS -X POST \
            -F "payload_json={\"content\":\"🎥 Nouvelle vidéo d'horreur générée automatiquement !\"}" \
            -F "files[0]=@work/final.mp4" \
            "$DISCORD_WEBHOOK_URL"