name: F - Publish to Discord

on:
  workflow_dispatch:

jobs:
  publish_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Download final video
        uses: actions/download-artifact@v4
        with:
          name: final_video
          path: work

      - name: Send to Discord
        run: |
          curl -F "payload_json={\"content\": \"Nouvelle vidéo générée !\"}" \
               -F "file=@work/final.mp4" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}