name: g_build_media_bank
on:
  workflow_call:

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: story_txt
          path: work
      - uses: actions/download-artifact@v4
        with:
          name: captions_srt
          path: work
      - uses: actions/download-artifact@v4
        with:
          name: voice_wav
          path: work
      - uses: actions/download-artifact@v4
        with:
          name: images_zip
          path: work
      - uses: actions/download-artifact@v4
        with:
          name: final_mp4
          path: work

      - name: Create media bank
        run: |
          mkdir -p outputs/media_bank
          cp work/story.txt outputs/media_bank/
          cp work/captions.srt outputs/media_bank/
          cp work/voice.wav outputs/media_bank/
          cp work/images.zip outputs/media_bank/
          cp work/final.mp4 outputs/media_bank/
          zip -r outputs/media_bank.zip outputs/media_bank

      - uses: actions/upload-artifact@v4
        with:
          name: media_bank_zip
          path: outputs/media_bank.zip