name: Build Media Bank

on:
  workflow_dispatch:
    inputs:
      theme:
        description: "Thème pour les médias"
        required: true
        default: "Horreur"

jobs:
  build_mediabank:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create folders
        run: |
          mkdir -p media_bank/images
          mkdir -p media_bank/videos

      - name: Download images from Pexels
        run: |
          for i in $(seq 1 100); do
            URL=$(curl -s "https://api.pexels.com/v1/search?query=${{ github.event.inputs.theme }}&per_page=1&page=$i" \
              -H "Authorization: ${{ secrets.PEXELS_API_KEY }}" | jq -r '.photos[0].src.original')
            wget -q -O "media_bank/images/${i}.jpg" "$URL"
          done

      - name: Download videos from Pixabay
        run: |
          for i in $(seq 1 100); do
            URL=$(curl -s "https://pixabay.com/api/videos/?key=${{ secrets.PIXABAY_API_KEY }}&q=${{ github.event.inputs.theme }}&per_page=1&page=$i" \
              | jq -r '.hits[0].videos.medium.url')
            wget -q -O "media_bank/videos/${i}.mp4" "$URL"
          done

      - name: Upload media bank artifact
        uses: actions/upload-artifact@v4
        with:
          name: media_bank
          path: media_bank