name: Build media bank

on:
  workflow_call:
    inputs:
      query:
        type: string
        required: false
        default: "horreur, peur, angoisse"
    secrets:
      PEXELS_API_KEY:
        required: false
      PIXABAY_API_KEY:
        required: false

jobs:
  bank:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare folders
        shell: bash
        run: |
          set -Eeuo pipefail
          mkdir -p bank/images bank/clips

      - name: Fetch from Pexels (if key)
        if: ${{ secrets.PEXELS_API_KEY != '' }}
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        shell: bash
        run: |
          set -Eeuo pipefail
          q=$(printf "%s" "${{ inputs.query }}" | tr ' ' '+')
          curl -sS -H "Authorization: $PEXELS_API_KEY" \
            "https://api.pexels.com/v1/search?query=$q&per_page=30" > pexels.json
          jq -r '.photos[].src.large' pexels.json | head -n 20 | xargs -I{} -n1 -P4 curl -sS -L {} -o "bank/images/pex_$(date +%s%N)_img.jpg"
          jq -r '.videos[].video_files[] | select(.quality=="sd") | .link' pexels.json | head -n 10 | xargs -I{} -n1 -P2 curl -sS -L {} -o "bank/clips/pex_$(date +%s%N)_clip.mp4" || true

      - name: Fetch from Pixabay (if key)
        if: ${{ secrets.PIXABAY_API_KEY != '' }}
        env:
          PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}
        shell: bash
        run: |
          set -Eeuo pipefail
          q=$(python3 - <<'PY'
          import urllib.parse, os
          print(urllib.parse.quote_plus(os.environ["Q"]))
PY
          )
        env:
          Q: ${{ inputs.query }}
        shell: bash
        run: |
          set -Eeuo pipefail
          curl -sS "https://pixabay.com/api/?key=${{ secrets.PIXABAY_API_KEY }}&q=$Q&image_type=photo&per_page=30" > pixa_img.json
          jq -r '.hits[].largeImageURL' pixa_img.json | head -n 20 | xargs -I{} -n1 -P4 curl -sS -L {} -o "bank/images/pixa_$(date +%s%N)_img.jpg"
          curl -sS "https://pixabay.com/api/videos/?key=${{ secrets.PIXABAY_API_KEY }}&q=$Q&per_page=20" > pixa_vid.json
          jq -r '.hits[].videos.tiny.url' pixa_vid.json | head -n 10 | xargs -I{} -n1 -P2 curl -sS -L {} -o "bank/clips/pixa_$(date +%s%N)_clip.mp4" || true

      - name: Upload media bank
        uses: actions/upload-artifact@v4
        with:
          name: media-bank
          path: bank
          retention-days: 7