name: g_build_media_bank

on:
  workflow_call:
    inputs:
      query:
        required: true
        type: string
      video_path:
        required: true
        type: string
      captions_path:
        required: true
        type: string
      voice_path:
        required: true
        type: string

permissions:
  contents: read

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with: { name: images_zip, path: . }
      - uses: actions/download-artifact@v4
        with: { name: final_video_mp4, path: . }
      - uses: actions/download-artifact@v4
        with: { name: subtitles_srt, path: . }
      - uses: actions/download-artifact@v4
        with: { name: voice_mp3, path: . }
      - uses: actions/download-artifact@v4
        with: { name: prompt_txt, path: . }
      - name: Packager bundle
        run: |
          mkdir -p bundle
          cp outputs/images.zip            bundle/
          cp ${{ inputs.video_path }}      bundle/
          cp ${{ inputs.captions_path }}   bundle/
          cp ${{ inputs.voice_path }}      bundle/
          cp outputs/prompt.txt            bundle/
          printf "%s\n" "${{ inputs.query }}" > bundle/image_query.txt
          (cd bundle && zip -r ../media_bank_bundle.zip .)
      - uses: actions/upload-artifact@v4
        with:
          name: media_bank_bundle
          path: media_bank_bundle.zip
          if-no-files-found: error
          retention-days: 30