name: g_build_mediabank

on:
  workflow_dispatch:
    inputs:
      theme:
        description: "Thème(s), séparés par des virgules (ex: horror,shadow,night)"
        required: false
        default: "horror"
      max_images:
        description: "Nombre d'images à récupérer (total)"
        required: false
        default: "100"
      max_videos:
        description: "Nombre de mini-clips à récupérer (total)"
        required: false
        default: "100"
      providers:
        description: "Sources (pexels,pixabay)"
        required: false
        default: "pexels,pixabay"

jobs:
  build_mediabank:
    runs-on: ubuntu-latest
    env:
      THEME: ${{ github.event.inputs.theme }}
      MAX_IMAGES: ${{ github.event.inputs.max_images }}
      MAX_VIDEOS: ${{ github.event.inputs.max_videos }}
      PROVIDERS: ${{ github.event.inputs.providers }}
      PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
      PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Préparer dossiers
        run: |
          set -euo pipefail
          mkdir -p media_bank/images media_bank/videos work
          echo "theme=${THEME}" > work/params.txt
          echo "providers=${PROVIDERS}" >> work/params.txt
          echo "max_images=${MAX_IMAGES}" >> work/params.txt
          echo "max_videos=${MAX_VIDEOS}" >> work/params.txt

      - name: Installer jq & curl
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Télécharger images (Pexels)
        if: contains(env.PROVIDERS, 'pexels')
        env:
          KEY: ${{ env.PEXELS_API_KEY }}
        run: |
          set -euo pipefail
          if [ -z "${KEY:-}" ]; then
            echo "Clé Pexels absente: skip."
            exit 0
          fi
          THEMES=$(echo "$THEME" | tr ',' ' ')
          COUNT=0
          MAX=$(( MAX_IMAGES / 2 ))
          if [ $MAX -lt 1 ]; then MAX=1; fi
          for kw in $THEMES; do
            if [ $COUNT -ge $MAX_IMAGES ]; then break; fi
            echo "Téléchargement d'images Pexels pour: $kw"
            # On demande 20 par page, on boucle sur 1..5 jusqu'à atteindre MAX (limite simple)
            for page in 1 2 3 4 5; do
              if [ $COUNT -ge $MAX_IMAGES ]; then break; fi
              url="https://api.pexels.com/v1/search?query=${kw}&per_page=20&page=${page}"
              json=$(curl -fsSL -H "Authorization: $KEY" "$url" || true)
              echo "$json" | jq -r '.photos[].src.original' | while read -r u; do
                if [ -n "$u" ] && [ $COUNT -lt $MAX_IMAGES ]; then
                  fn="media_bank/images/pexels_${kw}_${COUNT}.jpg"
                  curl -fsSL "$u" -o "$fn" || true
                  if [ -s "$fn" ]; then COUNT=$((COUNT+1)); fi
                fi
              done
            done
          done
          echo "Total images Pexels: $COUNT"

      - name: Télécharger images (Pixabay)
        if: contains(env.PROVIDERS, 'pixabay')
        env:
          KEY: ${{ env.PIXABAY_API_KEY }}
        run: |
          set -euo pipefail
          if [ -z "${KEY:-}" ]; then
            echo "Clé Pixabay absente: skip."
            exit 0
          fi
          THEMES=$(echo "$THEME" | tr ',' ' ')
          CUR=$(ls -1 media_bank/images 2>/dev/null | wc -l || true)
          REM=$(( MAX_IMAGES - CUR ))
          if [ $REM -le 0 ]; then
            echo "Quota images déjà atteint: $CUR"
            exit 0
          fi
          for kw in $THEMES; do
            if [ $REM -le 0 ]; then break; fi
            echo "Téléchargement d'images Pixabay pour: $kw"
            for page in 1 2 3 4 5; do
              if [ $REM -le 0 ]; then break; fi
              url="https://pixabay.com/api/?key=${KEY}&q=${kw}&image_type=photo&per_page=20&page=${page}"
              json=$(curl -fsSL "$url" || true)
              echo "$json" | jq -r '.hits[].largeImageURL' | while read -r u; do
                if [ -n "$u" ] && [ $REM -gt 0 ]; then
                  idx=$(ls -1 media_bank/images 2>/dev/null | wc -l || true)
                  fn="media_bank/images/pixabay_${kw}_${idx}.jpg"
                  curl -fsSL "$u" -o "$fn" || true
                  if [ -s "$fn" ]; then REM=$((REM-1)); fi
                fi
              done
            done
          done
          echo "Total images: $(ls -1 media_bank/images 2>/dev/null | wc -l || true)"

      - name: Télécharger vidéos (Pexels)
        if: contains(env.PROVIDERS, 'pexels')
        env:
          KEY: ${{ env.PEXELS_API_KEY }}
        run: |
          set -euo pipefail
          if [ -z "${KEY:-}" ]; then
            echo "Clé Pexels absente: skip vidéos."
            exit 0
          fi
          THEMES=$(echo "$THEME" | tr ',' ' ')
          COUNT=0
          for kw in $THEMES; do
            if [ $COUNT -ge $MAX_VIDEOS ]; then break; fi
            echo "Téléchargement de mini-clips Pexels pour: $kw"
            for page in 1 2 3 4 5; do
              if [ $COUNT -ge $MAX_VIDEOS ]; then break; fi
              url="https://api.pexels.com/videos/search?query=${kw}&per_page=15&page=${page}"
              json=$(curl -fsSL -H "Authorization: $KEY" "$url" || true)
              # On prend la plus petite version (première video_files) pour limiter la taille
              echo "$json" | jq -r '.videos[].video_files[0].link' | while read -r u; do
                if [ -n "$u" ] && [ $COUNT -lt $MAX_VIDEOS ]; then
                  fn="media_bank/videos/pexels_${kw}_${COUNT}.mp4"
                  curl -fsSL "$u" -o "$fn" || true
                  if [ -s "$fn" ]; then COUNT=$((COUNT+1)); fi
                fi
              done
            done
          done
          echo "Total vidéos Pexels: $COUNT"

      - name: Vérifier contenu et uploader artefact
        uses: actions/upload-artifact@v4
        with:
          name: media_bank
          path: media_bank
          if-no-files-found: error