name: Horror TikTok Builder (no-heredoc, full)

on:
  workflow_dispatch:
  push:
    branches: ["main"]

env:
  OUT_NAME: final_horror.mp4
  MANIFEST_FILE: manifests/horreur.txt

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
      ELEVENLABS_VOICE_ID: ${{ secrets.ELEVENLABS_VOICE_ID }}
      DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
      DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
      DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system deps
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python deps
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # ===================== STORY =====================
      - name: Generate story (gpt-4o, temp=1)
        run: |
          set -euo pipefail
          mkdir -p story
          python scripts/generate_story.py \
            --model gpt-4o \
            --temperature 1 \
            --system "Tu écris un script court et immersif d'horreur en français. N'inclus AUCUNE didascalie (intro, scène, narrateur, CTA, etc.). Raconte seulement l'histoire." \
            --user "Écris une histoire TikTok immersive (≈180-200 mots). Thème : horreur atmosphérique, manoir, pluie, bruits métalliques. Style concis, phrases courtes." \
            --out story/story.txt \
            --title-out story/title.txt
          test -s story/story.txt

      - name: Show story length
        run: |
          set -euo pipefail
          wc -w story/story.txt || true
          if [ -s story/title.txt ]; then echo "Title: $(cat story/title.txt)"; fi

      # ====================== TTS ======================
      - name: Synthesize voice (ElevenLabs)
        run: |
          set -euo pipefail
          mkdir -p audio
          python scripts/voice_elevenlabs.py \
            --transcript story/story.txt \
            --out audio/voice.wav
          test -s audio/voice.wav

      - name: Probe audio duration
        run: |
          set -euo pipefail
          ffprobe -v error -show_entries format=duration -of default=nk=1:nw=1 audio/voice.wav | tr -d '\r' || true

      # ============== SELECT & MERGE CLIPS =============
      - name: Select & merge clips from manifest (absolute paths)
        run: |
          set -euo pipefail
          mkdir -p selected_media
          test -s "${MANIFEST_FILE}"
          python scripts/select_and_merge.py \
            --manifest "${MANIFEST_FILE}" \
            --audio audio/voice.wav \
            --out selected_media/merged.mp4
          test -s selected_media/merged.mp4

      - name: Probe merged video
        run: |
          set -euo pipefail
          ffprobe -v error -show_entries format=duration -of default=nk=1:nw=1 selected_media/merged.mp4 || true

      # ================== SUBTITLES (ASS) ==============
      - name: Build ASS subtitles
        run: |
          set -euo pipefail
          mkdir -p subs
          python scripts/build_ass.py \
            --transcript story/story.txt \
            --audio audio/voice.wav \
            --out subs/captions.ass
          test -s subs/captions.ass
          head -n 25 subs/captions.ass || true

      # ===================== RENDER =====================
      - name: Render final video (effects + subs, cut to audio)
        run: |
          set -euo pipefail
          mkdir -p final_video
          python scripts/render_final.py \
            --video selected_media/merged.mp4 \
            --audio audio/voice.wav \
            --subs subs/captions.ass \
            --output "final_video/${OUT_NAME}"
          test -s "final_video/${OUT_NAME}"

      - name: Show final info
        run: |
          set -euo pipefail
          du -h "final_video/${OUT_NAME}" || true
          ffprobe -v error -show_entries format=duration -of default=nk=1:nw=1 "final_video/${OUT_NAME}" || true

      # =================== ARTIFACTS ====================
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_outputs
          path: |
            story/
            audio/
            subs/
            selected_media/
            final_video/

      # =================== DROPBOX ======================
      - name: Upload to Dropbox (refresh token auto)
        run: |
          set -euo pipefail
          : "${DROPBOX_APP_KEY:?missing}"
          : "${DROPBOX_APP_SECRET:?missing}"
          : "${DROPBOX_REFRESH_TOKEN:?missing}"
          python scripts/dropbox_upload.py \
            --file "final_video/${OUT_NAME}" \
            --remote-dir "/horror" \
            --out-link final_video/dropbox_link.txt
          test -s final_video/dropbox_link.txt || true