name: Horror TikTok Builder (no-heredoc, WhisperX)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  OUT_NAME: "final_horror.mp4"
  # Prompts (fr)
  SYSTEM_PROMPT: "Tu écris un script court et immersif d'horreur en français. N'inclus AUCUNE didascalie (intro, scène, narrateur, CTA, etc.). Raconte seulement l'histoire."
  USER_PROMPT: "Écris un script TikTok de 180 à 200 mots (65-75s). Thème : horreur atmosphérique, manoir, pluie, bruits métalliques. Style concis, phrases courtes, sans grossièretés."

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Secrets requis (refresh token Dropbox recommandé)
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
      ELEVENLABS_VOICE_ID: ${{ secrets.ELEVENLABS_VOICE_ID }}
      DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
      DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
      DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create folders
        run: |
          mkdir -p story audio subs selected_media final_video

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python dependencies (Torch CPU, WhisperX, etc.)
        run: |
          python -m pip install --upgrade pip
          pip install torch==2.3.1+cpu torchaudio==2.3.1+cpu --index-url https://download.pytorch.org/whl/cpu
          pip install whisperx==3.1.1 requests rich numpy

      # ---------- Génération du script ----------
      - name: Generate story (OpenAI)
        run: python scripts/generate_story.py
        env:
          SYSTEM_PROMPT: ${{ env.SYSTEM_PROMPT }}
          USER_PROMPT: ${{ env.USER_PROMPT }}

      # ---------- Voix ElevenLabs ----------
      - name: Synthesize voice (ElevenLabs)
        run: python scripts/voice_elevenlabs.py --input story/story.txt --output audio/voice.wav

      # ---------- Sous-titres WhisperX ----------
      - name: Build subtitles with WhisperX
        run: python scripts/whisperx_subs.py --audio audio/voice.wav --output subs/subtitles.srt

      # ---------- Sélection & Merge des clips (durée = voix) ----------
      - name: Select clips and merge (match voice duration)
        run: python scripts/select_and_merge.py --manifest manifests/horreur.txt --audio audio/voice.wav --output selected_media/merged.mp4

      # ---------- Rendu final (overlay SRT, rognage à la durée audio) ----------
      - name: Render final video
        run: python scripts/render_final.py --video selected_media/merged.mp4 --audio audio/voice.wav --subs subs/subtitles.srt --output final_video/${{ env.OUT_NAME }}

      # ---------- Upload Dropbox (Refresh Token) ----------
      - name: Upload to Dropbox
        run: python scripts/dropbox_upload.py --file final_video/${{ env.OUT_NAME }} --out final_video/dropbox_link.txt

      # ---------- Artifacts ----------
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: final_video
          path: |
            final_video/${{ env.OUT_NAME }}
            final_video/dropbox_link.txt