name: Horror TikTok Builder (no-heredoc, voice-length-cut)

on:
  workflow_dispatch:
  push:
    branches: ["main"]

env:
  OUT_NAME: "final_horror.mp4"
  SYSTEM_PROMPT: "Tu écris un script court et immersif d'horreur en français. N'inclus AUCUNE didascalie (intro, scène, narrateur, CTA, etc.). Raconte seulement l'histoire."
  USER_PROMPT: "Écris un script TikTok de 180 à 200 mots (65-75s). Thème : horreur atmosphérique, manoir, pluie, bruits métalliques. Style concis, phrases courtes, sans grossièretés."

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
      ELEVENLABS_VOICE_ID: ${{ secrets.ELEVENLABS_VOICE_ID }}
      MANIFEST_URL: ${{ secrets.MANIFEST_URL }}
      DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
      DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
      DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
      DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Python & install ffmpeg
        shell: bash
        run: |
          set -euo pipefail
          python3 --version
          sudo apt-get update -y
          sudo apt-get install -y ffmpeg

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate required secrets
        shell: bash
        run: |
          set -euo pipefail
          [ -n "${OPENAI_API_KEY:-}" ] || { echo "OPENAI_API_KEY manquant"; exit 1; }
          [ -n "${ELEVENLABS_API_KEY:-}" ] || { echo "ELEVENLABS_API_KEY manquant"; exit 1; }
          [ -n "${ELEVENLABS_VOICE_ID:-}" ] || { echo "ELEVENLABS_VOICE_ID manquant"; exit 1; }
          # Dropbox : soit ACCESS_TOKEN simple, soit trio APP_KEY/APP_SECRET/REFRESH_TOKEN
          if [ -z "${DROPBOX_ACCESS_TOKEN:-}" ]; then
            if [ -z "${DROPBOX_APP_KEY:-}" ] || [ -z "${DROPBOX_APP_SECRET:-}" ] || [ -z "${DROPBOX_REFRESH_TOKEN:-}" ]; then
              echo "Aucun token Dropbox valide (DROPBOX_ACCESS_TOKEN ou trio APP_KEY/APP_SECRET/REFRESH_TOKEN)."
              # On ne stoppe pas le build vidéo; on empêchera juste l'étape d'upload avec un if conditionnel
            fi
          fi

      - name: Generate story (no stage directions)
        shell: bash
        run: |
          set -euo pipefail
          python scripts/generate_story.py

      - name: Synthesize voice (ElevenLabs) + duration probe
        shell: bash
        run: |
          set -euo pipefail
          python scripts/voice_elevenlabs.py

      - name: Build background to match voice length (no black outro)
        shell: bash
        run: |
          set -euo pipefail
          python scripts/select_and_merge.py

      - name: Build subtitles (ASS with karaoke) from story & duration
        shell: bash
        run: |
          set -euo pipefail
          python subtitles/build_ass.py

      - name: Render final video (trim exactly to voice duration)
        shell: bash
        run: |
          set -euo pipefail
          python scripts/render_final.py

      - name: Upload artifacts (video + captions)
        uses: actions/upload-artifact@v4
        with:
          name: final_outputs
          path: |
            final_video/${{ env.OUT_NAME }}
            subtitles/captions.ass

      - name: Upload to Dropbox (if tokens available)
        if: ${{ env.DROPBOX_ACCESS_TOKEN != '' || (env.DROPBOX_APP_KEY != '' && env.DROPBOX_APP_SECRET != '' && env.DROPBOX_REFRESH_TOKEN != '') }}
        shell: bash
        run: |
          set -euo pipefail
          python scripts/dropbox_upload.py

      - name: Upload Dropbox link artifact (if created)
        if: ${{ env.DROPBOX_ACCESS_TOKEN != '' || (env.DROPBOX_APP_KEY != '' && env.DROPBOX_APP_SECRET != '' && env.DROPBOX_REFRESH_TOKEN != '') }}
        uses: actions/upload-artifact@v4
        with:
          name: dropbox_link
          path: final_video/dropbox_link.txt